const Product = [
    {
      id: 1,
      title: "White Roses",
      description: "A bouquet of white roses",
      price: "₹ 400",
      img: "/image/Rose1.png",
      quantity: 0,
      type: "Flower",
    },
    {
      id: 2,
      title: "Red Roses",
      description: "A bouquet of red roses",
      price: "₹ 200",
      img: "/image/Rose2.png",
      quantity: 0,
      type: "Flower",
    },
    {
      id: 3,
      title: "Elegant Roses",
      description: "A bouquet of pink roses",
      price: "₹ 600",
      img: "/image/Rose3.png",
      quantity: 0,
      type: "Flower",
    },
    {
      id: 4,
      title: "Blue Roses",
      description: "A bouquet full of blue roses",
      price: "₹ 900",
      img: "/image/Rose4.png",
      quantity: 0,
      type: "Flower",
    },
    {
      id: 5,
      title: "B&W Roses",
      description: "A bouquet full of B&W roses",
      price: "₹ 900",
      img: "/image/Rose5.png",
      quantity: 0,
      type: "Flower",
    },
    {
      id: 6,
      title: "Lillys",
      description: "A bouquet of beautiful Lillys",
      price: "₹ 500",
      img: "/image/Lilly1.png",
      quantity: 0,
      type: "Flower",
    },
    {
      id: 7,
      title: "Wild Lillys",
      description: "A bouquet of beautiful Lillys",
      price: "₹ 600",
      img: "/image/Lilly2.png",
      quantity: 0,
      type: "Flower",
    },
    {
      id: 8,
      title: "Pink Lillys",
      description: "A bouquet of Pink Lillys",
      price: "₹ 800",
      img: "/image/Lilly3.png",
      quantity: 0,
      type: "Flower",
    },
    {
      id: 9,
      title: "Lilly bouquet",
      description: "A bouquet of beautiful Lillys",
      price: "15000",
      img: "/image/Lilly4.png",
      quantity: 0,
      type: "Flower",
    },
    {
      id: 10,
      title: "Pink bouquet",
      description: "A bouquet of Pink Lillys",
      price: "15000",
      img: "/image/Lilly5.png",
      quantity: 0,
      type: "Flower",
    },
    {
      id: 11,
      title: "Lavender bouquet",
      description: "A small bouquet of Lavender",
      price: "1000",
      img: "/image/Lavender1.png",
      quantity: 0,
      type: "Flower",
    },
    {
      id: 12,
      title: "Lavender bouquet",
      description: "A big bouquet of Lavender",
      price: "5000",
      img: "/image/Lavender2.png",
      quantity: 0,
      type: "Flower",
    },
    {
      id: 13,
      title: "Lavender bouquet",
      description: "A Lavender bouquet combo",
      price: "2000",
      img: "/image/Lavender3.png",
      quantity: 0,
      type: "Flower",
    },
    {
      id: 14,
      title: "Large bouquet",
      description: "A large bouquet of Lavender",
      price: "5500",
      img: "/image/Lavender4.png",
      quantity: 0,
      type: "Flower",
    },
    {
      id: 15,
      title: "Lavender bouquet",
      description: "A bouquet of Lavender",
      price: "1000",
      img: "/image/Lavender5.png",
      quantity: 0,
      type: "Flower",
    },
    {
      id: 16,
      title: "Truffle Cake",
      description: "Eggless Green Truffle Cake",
      price: "₹ 1600",
      img: "/image/Cake1.png",
      quantity: 0,
      type: "Cake",
    },
    {
      id: 17,
      title: "Caramel Cake",
      description: "Floral themed Caramel cake",
      price: "₹ 2600",
      img: "/image/Cake2.png",
      quantity: 0,
      type: "Cake",
    },
    {
      id: 18,
      title: "Fairy Cake",
      description: "Floral themed Fairy cake",
      price: "₹ 2600",
      img: "/image/Cake3.png",
      quantity: 0,
      type: "Cake",
    },
    {
      id: 19,
      title: "Blue Cake",
      description: "Beautiful sea themed cake",
      price: "₹ 3600",
      img: "/image/Cake4.png",
      quantity: 0,
      type: "Cake",
    },
    {
      id: 20,
      title: "Graphic Cake",
      description: "Unique Graphic themed cake",
      price: "₹ 3000",
      img: "/image/Cake5.png",
      quantity: 0,
      type: "Cake",
    },
    {
      id: 21,
      title: "Caramel Cake",
      description: "Caramel flavored cake",
      price: "₹ 2600",
      img: "/image/Ccakes1.png",
      quantity: 0,
      type: "Cake",
    },
    {
      id: 22,
      title: "Choco Cake",
      description: "Chocolate flavored cake",
      price: "₹ 3000",
      img: "/image/Ccakes2.png",
      quantity: 0,
      type: "Cake",
    },
    {
      id: 23,
      title: "Strawberry Cake",
      description: "Strawberry flavored cake",
      price: "₹ 2800",
      img: "/image/Ccakes3.png",
      quantity: 0,
      type: "Cake",
    },
    {
      id: 24,
      title: "Vanilla Cake",
      description: "Vanilla flavored cake",
      price: "₹ 2500",
      img: "/image/Ccakes4.png",
      quantity: 0,
      type: "Cake",
    },
    {
      id: 25,
      title: "Coffee Cake",
      description: "Coffee flavored cake",
      price: "₹ 3200",
      img: "/image/Ccakes5.png",
      quantity: 0,
      type: "Cake",
    },
    {
      id: 26,
      title: "Mocha Coffee",
      description: "Mocha flavored coffee",
      price: "₹ 300",
      img: "/image/Coffee1.png",
      quantity: 0,
      type: "Coffee",
    },
    {
      id: 27,
      title: "Cappuccino",
      description: "Cappuccino flavored coffee",
      price: "₹ 350",
      img: "/image/Coffee2.png",
      quantity: 0,
      type: "Coffee",
    },
    {
      id: 28,
      title: "Espresso",
      description: "Espresso flavored coffee",
      price: "₹ 400",
      img: "/image/Coffee3.png",
      quantity: 0,
      type: "Coffee",
    },
    {
      id: 29,
      title: "Latte",
      description: "Latte flavored coffee",
      price: "₹ 450",
      img: "/image/Coffee4.png",
      quantity: 0,
      type: "Coffee",
    },
    {
      id: 30,
      title: "Mochaccino",
      description: "Mochaccino flavored coffee",
      price: "₹ 500",
      img: "/image/Coffee5.png",
      quantity: 0,
      type: "Coffee",
    },
    {
      id: 31,
      title: "Dairymilk",
      description: "10 Dairymilk in a hamper",
      price: "₹ 400",
      img: "/image/Chocolate1.png",
      quantity: 0,
      type: "Chocolate",
    },
    {
      id: 32,
      title: "Dairymilk Combo",
      description: "22 Dairymilk in a hamper",
      price: "₹ 700",
      img: "/image/Chocolate2.png",
      quantity: 0,
      type: "Chocolate",
    },
    {
      id: 33,
      title: "KitKat Combo",
      description: "22 KitKat in a gift hamper",
      price: "₹ 700",
      img: "/image/Chocolate3.png",
      quantity: 0,
      type: "Chocolate",
    },
    {
      id: 34,
      title: "Chocolate Combo",
      description: "KitKat and DairyMilk Combo",
      price: "₹ 1000",
      img: "/image/Chocolate4.png",
      quantity: 0,
      type: "Chocolate",
    },
    {
      id: 35,
      title: "Chocolate Combo",
      description: "Snikers and KitKat Combo",
      price: "₹ 1000",
      img: "/image/Chocolate5.png",
      quantity: 0,
      type: "Chocolate",
    },
    {
      id: 36,
      title: "Louis Vuitton",
      description: "Louis Vuitton wallet",
      price: "₹ 15000",
      img: "/image/Men1.png",
      quantity: 0,
      type: "Men's Fashion",
    },
    {
      id: 37,
      title: "Prada Wallet",
      description: "Prada Leather Wallet",
      price: "₹ 12000",
      img: "/image/Men2.png",
      quantity: 0,
      type: "Men's Fashion",
    },
    {
      id: 38,
      title: "Jimmy Choo",
      description: "Jimmy Choo Perfume for men",
      price: "₹ 5000",
      img: "/image/Men3.png",
      quantity: 0,
      type: "Men's Fashion",
    },
    {
      id: 39,
      title: "Louis Vuitton",
      description: "Louis Vuitton leather wallet",
      price: "₹ 15000",
      img: "/image/Men4.png",
      quantity: 0,
      type: "Men's Fashion",
    },
    {
      id: 40,
      title: "CHANEL BLEU",
      description: "CHANEL BLEU fragnance",
      price: "₹ 15000",
      img: "/image/Men6.png",
      quantity: 0,
      type: "Men's Fashion",
    },
    {
      id: 41,
      title: "CHANEL CHANCE",
      description: "Chanel Chance fragnance",
      price: "₹ 4000",
      img: "/image/Wife1.png",
      quantity: 0,
      type: "Women's Fashion",
    },
    {
      id: 42,
      title: "CHANEL N°5",
      description: "Chanel N°5 fragnance",
      price: "₹ 7000",
      img: "/image/Wife2.png",
      quantity: 0,
      type: "Women's Fashion",
    },
    {
      id: 43,
      title: "DIOR JoY",
      description: "DIOR JoY fragnance",
      price: "₹ 27000",
      img: "/image/Wife3.png",
      quantity: 0,
      type: "Women's Fashion",
    },
    {
      id: 44,
      title: "JALooR",
      description: "JALooR fragnance",
      price: "₹ 17000",
      img: "/image/Wife4.png",
      quantity: 0,
      type: "Women's Fashion",
    },
    {
      id: 45,
      title: "CHANEL CHANCE",
      description: "CHANEL CHANCE fragnance",
      price: "₹ 20000",
      img: "/image/Wife5.png",
      quantity: 0,
      type: "Women's Fashion",
    },
    {
      id: 46,
      title: "Perfume & watch",
      description: "Combo For Couples",
      price: "₹ 3000",
      img: "/image/Couple1.png",
      quantity: 0,
      type: "Couples",
    },
    {
      id: 47,
      title: "Watch Combo",
      description: "Combo For Couples",
      price: "₹ 4000",
      img: "/image/Couple2.png",
      quantity: 0,
      type: "Couples",
    },
    {
      id: 48,
      title: "Bracelet",
      description: "Beautiful Bracelet",
      price: "₹ 5000",
      img: "/image/Couple3.png",
      quantity: 0,
      type: "Couples",
    },
    {
      id: 49,
      title: "Chain",
      description: "Beautiful Chain",
      price: "₹ 2000",
      img: "/image/Couple4.png",
      quantity: 0,
      type: "Couples",
    },
    {
      id: 50,
      title: "Gift Combo",
      description: "Couple Gift Combo",
      price: "₹ 5000",
      img: "/image/Couple5.png",
      quantity: 0,
      type: "Couples",
    },
  ];
  
  export default Product;
  